### ISSUE TITLE
Why is the blog not wide?

### ISSUE THREAD

**Issue by maelle** [amoeba/brycemecum.com#5]
@amoeba I was reading https://brycemecum.com/2020/08/05/testing-r-api-packages/ on my big screen (not bragging :joy:) and it only uses part of the width because of 

https://github.com/amoeba/brycemecum.com/blob/9d86d24cf2bb3c28fb4a0cd4a0a58b01b8e3a2da/_includes/styles.scss#L14

**Comment by maelle** [comment]
(I really liked reading the post, in any case, so thank you :pray: )

**Comment by amoeba** [comment]
Thanks for reading! I keep the page content within a maximum width because I've seen tons of people over the years suggest doing so for readability and I think I prefer it that way too. The idea is that it's hard for the eye to scan to the next line when lines get sufficiently long.

Would your preference be to let the line width fill the viewport, i.e., let the user decide where to wrap?

**Comment by maelle** [comment]
I see, it makes sense.

For me the problem was that the text was on the left of my screen. I'd be ok with the limited width if it were centered so I didn't have to turn my head :wink:

**Comment by amoeba** [comment]
Gotcha :) I might change things in the future but I think I'll keep it as-is for now.
